research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

sitemap_task:
  description: >
    Create a comprehensive repository overview:
    1. Generate a complete file tree (up to 5 levels deep) of {root_path}
    2. List and describe main directories and their purpose
    3. Document key files and their roles
    4. Keep individual descriptions under 100 words
    5. Add timestamp at the bottom in the format: "Last updated: YYYY-MM-DD HH:mm:ss"
    Focus on providing both broad structure via file tree and specific details about key components.
  expected_output: >
    A comprehensive markdown document with:
    1. Complete file tree (up to 5 levels)
    2. Root structure explanation
    3. Key component descriptions
    4. Important relationships
    5. Last updated timestamp in specified format
    Format the file tree with proper markdown code block formatting.
    Keep descriptions clear and concise.
    Total content should be under 2000 words (excluding file tree).
  agent: sitemap_maintainer
  output_file: docs/sitemap.md

validation_task:
  description: >
    Analyze documentation coverage and gaps:
    1. Check documentation in apps/docs/src/content/docs
    2. Review main documentation files in each app directory
    3. Compare against expected documentation:
       - README files
       - Setup instructions
       - API documentation
       - Development guides
       - Architecture documentation
    4. List critical missing documentation
    5. Suggest practical fixes
    Keep analysis focused on major gaps affecting project understanding.
  expected_output: >
    A concise report containing:
    1. List of critical documentation gaps (max 5)
    2. Quick fix suggestions for each gap
    3. Priority level for each gap (High/Medium/Low)
    Keep total length under 500 words.
    Format in markdown with clear sections.
  agent: docs_validator
  output_file: docs/validation_report.md
